- name: nopcommarce install application
  hosts: webserver
  become: yes
  tasks:
    - name: os fail 
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: Install prince
     apt:
         deb: "{{microsoft_url}}"
         dpkg_options: packages-microsoft-prod.deb
    
      