--- 
- name: install nop commerce
  hosts: webserver
  become: yes
  tasks:
    - name: fail for unsuported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: Fetch a file from a URL
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb 
        dest: /home/ubuntu/packages-microsoft-prod.deb
    - name: useing cmd
      ansible.builtin.command:
        cmd: dpkg -i /home/ubuntu/packages-microsoft-prod.deb
    - name: install dot net application
      ansible.builtin.apt:
        name: "{{ dot_package }}"
        update_cache: yes
        state: "present"
    # install nginx
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/www/nopCommerce
        state: directory
        mode: '0755' 
    - name: download nop application
      ansible.builtin.get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.6/nopCommerce_4.60.6_NoSource_linux_x64.zip
        dest: /home/ubuntu/nopCommerce_4.60.6_NoSource_linux_x64.zip
    - name: unzip nop application
      ansible.builtin.unarchive: 
        src: /home/ubuntu/nopCommerce_4.60.6_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
        remote_src: yes
    - name: create a group
      ansible.builtin.group:
        name: nop
        state: "present"
    - name: create user nop
      ansible.builtin.user: 
        name: nop
        group: nop
        state: "present"
    - name: Create a directory 
      ansible.builtin.file:
        path: /var/www/nopCommerce/logs
        state: directory
        owner: nop
        group: nop
        mode: '0755'
    - name: Create a directory 
      ansible.builtin.file:
        path: /var/www/nopCommerce/bin
        owner: nop
        group: nop
        state: directory
        mode: '0755' 
    - name: change permission of directory
      ansible.builtin.file: 
        path: /var/www/nopCommerce
        owner: nop
        group: nop
        mode: '0755'
    - name: create nop service file 
      ansible.builtin.template:
        src: files/nopcommerce.service.j2
        dest: /etc/systemd/system/nopCommerce.service
        owner: root
        group: root
        mode: '0644'
        remote_src: yes
      notify:
        - start nopcommerce
  handlers:
    - name: start nopcommerce
      ansible.builtin.service:
        name: nopCommerce.service
        enabled: yes
        state:  restarted
    
         
      
