--- 
- name: install nopcommerce on ubuntu 
  hosts: webserver
  become: yes
  tasks:
    - name: fail for unsupported os family 
      ansible.builtin.fail: 
        msg: this works only on Ubuntu os
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: install microsoft packages 
      ansible.builtin.get_url:
        url: "{{ microsoft_url }}"
        dest: /home/ubuntu/packages-microsoft-prod.deb 
    -  name: microsoft prod 
       ansible.builtin.command: "{{ dpkg_package }}"
    -  name: install packages 
       ansible.builtin.apt:
         name: "{{ package_name }}"
         update_cache: yes
         state: present
    - name: install nginx
      ansible.builtin.apt:
        name: "{{ package }}"
        state: present
      notify:
        - start nginx 
    - name: create a directory 
      ansible.builtin.file:
        path: "/var/nop/nopCommerce"
        state: directory
    - name: Install unzip package
      become: yes
      apt:
        name: unzip
        state: present
    - name: create user 
      ansible.builtin.user:
        name: "{{ nop_owner }}"
        state: present 
    - name: create group 
      ansible.builtin.group:
        name: "{{ nop_group }}"
        state: present 
    - name: download zip 
      ansible.builtin.get_url:
        url: "{{ nop_package }}"
        dest: "/var/nop/nopCommerce"
    - name: Extract the archive
      ansible.builtin.unarchive:
        src: "{{ nop_package }}"
        dest: "/var/nop/nopCommerce"
        owner: "{{ nop_owner }}"
        group: "{{ nop_group }}"
        remote_src: yes
      become: yes
    - name: check the file exists
      ansible.builtin.stat:
        path: "/var/nop/nopCommerce"
    - name: create a directory 
      ansible.builtin.file:
        path: "/var/nop/nopCommerce/bin" 
        state: directory
        mode: '0755'
    - name: create a directory 
      ansible.builtin.file:
        path: "/var/nop/nopCommerce/logs" 
        state: directory
        mode: '0755'
    - name: changing ownership 
      ansible.builtin.file:
        path: "/var/nop/nopCommerce"
        owner: "{{ nop_owner }}"
        group: "{{ nop_group }}"
        recurse: true
        mode: '0755'
    - name: adding templates
      ansible.builtin.template:
        src: "templates/nopcommerce.j2"
        dest: "/etc/systemd/system/nopCommerce.service"
        owner: "{{ nop_owner }}"
        group: "{{ nop_group }}"
      notify:
        - start nopCommerce
        - restart nginx
  handlers: 
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
    - name: start nopCommerce 
      ansible.builtin.systemd:
        name: nopCommerce 
        daemon_reload: true
        enabled: true 
        state: started
    - name: restart nginx 
      ansible.builtin.service:
        name: nginx  
        state: restarted