---
- name: intall application in ubuntu
  hosts: webserver
  become: yes
  tasks:
    - name: fail for unsuported os
      ansible.builtin.fail:
        msg: "This playbook is designed only for Ubuntu os"
      when: ansible_facts['distribution'] != 'Ubuntu'
    - name: Fetch a file from a URL
      ansible.builtin.get_url:
        url: " https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb "
        dest: "/home/dell"
    - ansible.builtin.debug:
         msg: "Microsoft key  is installed using package "
    - name: Install Microsoft package
      ansible.builtin.command:
        cmd: dpkg -i packages-microsoft-prod.deb
    - ansible.builtin.debug:
         msg: "dotnet is installed using package {{ package1}}"
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Microsoft package
      ansible.builtin.apt:
        deb: /home/dell/packages-microsoft-prod.deb
        state: present
    - name: Install Microsoft package-1
      ansible.builtin.apt:
        name: "{{ dotnet_packages }}"
        update_cach: yes
        state: "present"
    - name: install in inginx webserver
      ansible.builtin.apt:
        name: "{{ ng_package }}"
        state: "present"
    
      
      
    
